### ISSUE TITLE
Tracking elements for on the fly appearence changes

### ISSUE THREAD

**Issue by Ekhorn** [Ekhorn/spaced#24]
### Description

One feature that Spaced should support is the possibility to click any element in mode <name-missing> that will help with on the fly editing of the appearance of elements.

The tracking can be done through [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) attributes.

### Requirements

- [ ] Must decide on a name for this mode.
- [ ] Must implement toggling this mode.
- [ ] Must add the relevant types:
  - [ ] Items should have `data-type=item`
  - [ ] Background should have `data-type=background`
  - [ ] Controls/Actions should have `data-type=control/action`
